version: 0.2

runtime-versions:
  ruby: 2.6
  nodejs: 10

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-frontend-ui-integration"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-integration-login"
    PAAS_PW: "epbr-govpaas-integration-pw"
    PAAS_SPACE: "epbr-govpaas-integration-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_AUTH_CLIENT_ID: "epbr-frontend-auth-client-id-integration"
    EPB_AUTH_CLIENT_SECRET: "epbr-frontend-auth-client-secret-integration"
    EPB_AUTH_SERVER: "epbr-auth-server-integration"
    EPB_API_URL: "epbr-api-url-integration"

phases:
  install:
    runtime-versions:
      ruby: 2.6
      nodejs: 10
    commands:
      - gem install bundler:2.0.2
      - bundle install
      - npm install
      - make journey
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO INTEGRATION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf v3-cancel-zdt-push ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
  post_build:
    commands:
      - cf logout
