version: 0.2

runtime-versions:
  ruby: 2.6
  nodejs: 10

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-frontend-ui-integration"

  parameter-store:
    PAAS_LOGIN_INTEGRATION: "epbr-govpaas-integration-login"
    PAAS_PW_INTEGRATION: "epbr-govpaas-integration-pw"
    PAAS_SPACE_INTEGRATION: "epbr-govpaas-integration-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"

phases:
  install:
    runtime-versions:
      ruby: 2.6
      nodejs: 10
    commands:
      - gem install bundler:2.0.2
      - bundle install
      - npm install
  build:
    commands:
      - make frontend-build
      - scripts/generate-paas-manifest.sh $DEPLOY_APPNAME > manifest.yml
      - echo ">>>>>>>> DEPLOY TO INTEGRATION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN_INTEGRATION -p "$PAAS_PW_INTEGRATION" -o $PAAS_ORG -s $PAAS_SPACE_INTEGRATION
      - cf v3-apply-manifest -f manifest.yml
      - cf v3-zdt-push $DEPLOY_APPNAME --wait-for-deploy-complete
      - cf logout
