version: 0.2

runtime-versions:
  ruby: 2.6
  nodejs: 10

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-frontend-ui-integration"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-integration-login"
    PAAS_PW: "epbr-govpaas-integration-pw"
    PAAS_SPACE: "epbr-govpaas-integration-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"

phases:
  install:
    runtime-versions:
      ruby: 2.6
      nodejs: 10
    commands:
      - gem install bundler:2.0.2
      - bundle install
      - npm install
  build:
    commands:
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - echo ">>>>>>>> DEPLOY TO INTEGRATION ENV"
      - make deploy-app
      - cf logout
