version: 0.2

runtime-versions:
  nodejs: 10  

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-frontend-ui-production"

  parameter-store:
    PAAS_LOGIN_PRODUCTION: "epbr-govpaas-production-login"
    PAAS_PW_PRODUCTION: "epbr-govpaas-production-pw"
    PAAS_SPACE_PRODUCTION: "epbr-govpaas-production-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
      - echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - apt-get update
      - apt-get install cf-cli
      - npm install
  build:
    commands:
      - npm run build
      - scripts/generate-paas-manifest.sh $DEPLOY_APPNAME > manifest.yml
      - echo ">>>>>>>> DEPLOY TO PRODUCTION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN_PRODUCTION -p "$PAAS_PW_PRODUCTION" -o $PAAS_ORG -s $PAAS_SPACE_PRODUCTION
      - cf v3-apply-manifest -f manifest.yml
      - cf v3-zdt-push $DEPLOY_APPNAME --wait-for-deploy-complete
      - cf logout
